services:
  - type: web
    name: school-memories
    runtime: docker
    plan: free
    branch: master
    region: oregon
    rootDir: school-memories
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
